global: &global
    adapter: mysql

production:
    host: db3.atp.bz
    database: www
    username: rails
    password: "2552877"
    socket: /tmp/mysql.sock
    <<: *global

development:    
    database: www
    username: root
    password: jess1024
    socket: /tmp/mysql.sock
    <<: *global

test: &test    
    database: www
    username: root
    password: jess1024
    socket: /tmp/mysql.sock
    <<: *global

cucumber:
    <<: *test
