global: &global
  adapter: mysql
  username: root
  password: jess1024
  socket: /tmp/mysql.sock

development:
  database: testimonial
  <<: *global

test: &test
  database: testimonial_test
  <<: *global

cucumber:
  <<: *test
